remote_theme: "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin: "dark"

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache

title: "Waihon Yew's Portfolio"
title_separator: "|"
description: "This is my portfolio site. Come and find out more!"
